kind: Service
apiVersion: v1
metadata:
  name: {{ .Values.name | quote }}
  annotations:
    description: Exposes and load balances the application pods
spec:
  type: NodePort
  ports:
  - name: web
    port: 8080
    targetPort: 8080
    nodePort: 30007
  selector:
    name: {{ .Values.name | quote }}
